background/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from background.views import test_index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bg.urls')),
]

bg/urls.py
from django.urls import path
import bg.views.index_views as index
import bg.views.live_or_die_views as ld
import bg.views.hell_money_views as hm
import bg.views.hell_views as ex

app_name = "bg"

urlpatterns = []

# 首页
urlpatterns += [
    path('', index.index)
]


# 生死簿
urlpatterns += [
    path('bg/people_page/', ld.UserManagement.as_view()),
    path('bg/dispose_page/', ld.UserDispose.as_view()),
    path('bg/reincarnation_page/', ld.Reincarnation.as_view()),
]


# 十八层地狱
urlpatterns += [
    path('bg/explain_page/', ex.Explain.as_view()),
    path('bg/punish_page/', ex.Punish.as_view()),
]


# 冥币管理
urlpatterns += [
    path('bg/money_page/', hm.HallMoney.as_view()),
    path('bg/hall_money/', hm.dispose_hall_money, name="dispose_hall_money"),
    path('bg/money_pay/', hm.HallMoneyPay.as_view()),
]

bg/models.py
from django.db import models

# Create your models here.

background/views.py
from django.shortcuts import render


def test_index(request):
    return render(request, "adminlte\index.html")

bg/views/base_views.py
from django.shortcuts import render
from django.views import View
from bg.helper.bg_page_helper import PageHelper

import logging
log = logging.getLogger()


class BaseView(View):
    title = ""
    b_model = ""  # 隶属的管理模块
    headers = []
    page = ""  # 页面

    def search(self, page_helper: PageHelper):
        pass

    def get(self, request, *args, **kwargs):
        page_helper = PageHelper(request)
        page_helper["active_page"] = self.title
        page_helper["active"] = self.b_model
        page_helper["headers"] = self.headers
        page_helper["data_list"] = []
        self.search(page_helper)
        return render(request, self.page, context=page_helper)

    def post(self, request, *args, **kwargs):
        page_helper = PageHelper(request)
        page_helper["active_page"] = self.title
        page_helper["active"] = self.b_model
        page_helper["headers"] = self.headers
        page_helper["data_list"] = []
        self.search(page_helper)
        return render(request, self.page, context=page_helper)

bg/views/hell_money_views.py
from django.contrib import messages
from django.shortcuts import render
from bg.config.menu import register_model
from bg.helper.bg_page_helper import PageHelper
from bg.views.base_views import BaseView


b_model = register_model["hell_money"]


class HallMoney(BaseView):
    title = "冥币管理"
    b_model = b_model
    page = "hell_money/hell_money.html"


def dispose_hall_money(request):
    name = request.POST.get("name")
    money = request.POST.get("name", 0)
    remark = request.POST.get("remark")

    messages.info(request, f"{name} 因 {remark} 奖励 {money} 冥币 ！！！！")
    return render(request, "hell_money/hell_money.html", context=PageHelper(request))


class HallMoneyPay(BaseView):
    title = "冥币薪资流水"
    b_model = b_model
    page = "index.html"

bg/views/hell_views.py
from bg.config.menu import register_model
from bg.views.base_views import BaseView


b_model = register_model["hell"]


class Explain(BaseView):
    """
    投胎记录
    """
    title = "十八层地狱说明"
    headers = []
    b_model = b_model
    page = "index.html"


class Punish(BaseView):
    """
    处罚流程
    """
    title = "处罚流程"
    headers = []
    b_model = b_model
    page = "index.html"

bg/views/index_views.py
from django.shortcuts import render
from bg.helper.bg_page_helper import PageHelper

import logging
log = logging.getLogger()


def index(request):
    context = PageHelper(request)
    return render(request, 'index.html', context=context)

bg/views/live_or_die_views.py
from bg.config.menu import register_model, register_page
from bg.helper.bg_page_helper import PageHelper
from bg.views.base_views import BaseView


b_model = register_model["live_or_die"]


class UserManagement(BaseView):
    title = "用户管理"
    headers = ["死亡时间", "死者名字", "性别", "死亡原因"]
    b_model = b_model
    page = "live_or_die/user_management.html"

    def search(self, page_helper: PageHelper):
        """
        随便返回几条数据
        """
        page_helper["data_list"] = [
            ["2022-07-08", "安倍晋三", "男", "死于正义之士枪杀"],
            ["2022-07-06", "张三", "男", "自然死亡"],
            ["2022-07-05", "李四", "男", "自然死亡"],
            ["2022-07-06", "张三2", "男", "自然死亡"],
            ["2022-07-05", "李四2", "男", "自然死亡"],
            ["2022-07-06", "张三3", "男", "自然死亡"],
            ["2022-07-05", "李四4", "男", "自然死亡"],
        ]


class UserDispose(BaseView):
    """
    用户处理
    """
    title = "用户处理"
    headers = []
    b_model = b_model
    page = "index.html"


class Reincarnation(BaseView):
    """
    投胎记录
    """
    title = "投胎记录"
    headers = []
    b_model = b_model
    page = "index.html"

bg/templates/hell_money/hell_money.html
`{% extends 'adminlte/base.html' %}
{% load static %}

{% block content %}
    <div>
        <form  method="post" action="{% url 'bg:dispose_hall_money' %}">
            {% csrf_token %}
            <div class="card-body">
              <div class="form-group">
                <label for="exampleInputEmail1">名字</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="输入名字">
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1">加冥币</label>
                <input type="number" class="form-control" id="money" name="money" placeholder="请输入冥币数量">
              </div>

              <div class="form-group">
                <label for="exampleInputEmail1">备注</label>
                <input type="text" class="form-control" id="remark" name="remark" placeholder="备注">
              </div>
            </div>
            <!-- /.card-body -->

            <div class="card-footer">
              <button type="submit" class="btn btn-primary">提交</button>
            </div>
        </form>
    </div>
{% endblock %}`

bg/templates/index.html
{% extends 'adminlte/base.html' %}
{% load static %}

{% block content %}
    <div>
        <h2 style="text-align: center">修改后的主页</h2>
        <h2 style="text-align: center">微信搜索"python小dem0"公众号，获取更多的demo</h2>
        <div style="text-align: center;padding: auto;">
            <p>微信公众号二维码</p>
            <img src="{% static 'image/gzh.jpg' %}">
        </div>
    </div>
{% endblock %}

bg/templates/live_or_die/user_management.html
{% extends 'adminlte/base.html' %}
{% load static %}

{% block content %}
    <div>
        <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">死亡用户列表</h3>

                <div class="card-tools">
                  <div class="input-group input-group-sm" style="width: 150px;">
                    <input type="text" name="table_search" class="form-control float-right" placeholder="搜索">

                    <div class="input-group-append">
                      <button type="submit" class="btn btn-default">
                        <i class="fas fa-search"></i>
                      </button>
                    </div>
                  </div>
                </div>
              </div>
              <!-- /.card-header -->
              <div class="card-body table-responsive p-0" style="height: 300px;">
                <table class="table table-head-fixed text-nowrap">
                  <thead>
                    <tr>
                        {% for h in headers %}
                            <th>{{ h }}</th>
                        {% endfor %}
                    </tr>
                  </thead>
                  <tbody>
                    {% for data in  data_list %}
                        <tr>
                            {% for td_data in data %}
                                <td>{{ td_data }}</td>
                            {% endfor %}
                        </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
    </div>
{% endblock %}

templates/adminlte/base.html
{% load adminlte_helpers i18n %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    {% block title_outer %}
        <title>{% block title %}{{ site.name }}{% endblock %}</title>
    {% endblock %}

    {% block meta %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-COMPATIBLE" content="IE=edge">
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    {% endblock %}

    {% block stylesheets %}
        {% include 'adminlte/lib/_styles.html' %}
        {% block style_sheets %}{% endblock %}
    {% endblock %}
    {% block extra_head %}{% endblock %}
</head>
<body class="hold-transition sidebar-mini {% block body_class %}{% block bodyclass %}layout-fixed {% endblock %}{% endblock %}">

{% block body %}
    <div class="wrapper">
        {% block nav_header %}
            {% include 'adminlte/lib/_main_header.html' %}
        {% endblock %}

        {% block nav_sidebar %}
            {% include 'adminlte/lib/_main_sidebar.html' %}
        {% endblock %}

        {% block content_wrapper %}
        <div class="content-wrapper">
            {% block content_header %}
                <section class="content-header">
                    {% block no_heading %}
                        <h1>
                            {% block page_name %}{% endblock %}
                            <div class="header-actions">
                                {% block page_actions %}{% endblock %}
                            </div>
                            {% block no_description %}
                            <small>{% block page_description %}{% endblock %}</small>
                            {% endblock %}
                        </h1>
                        {% block breadcrumbs %}
                            {# Breadcrumb implementation left to developers #}
                        {% endblock %}
                    {% endblock no_heading %}
                </section>
            {% endblock %}

            {% block content_outer %}
            <section class="content">
                {% block messages %}
                    {% include 'adminlte/lib/_messages.html' %}
                {% endblock %}

                {% block content_block_wrap %}
                    {% block content %}{% endblock %}
                {% endblock %}
            </section>
            {% endblock %}

        </div>
        {% endblock content_wrapper %}
        
        {% block nav_footer %}
            {% include 'adminlte/lib/_main_footer.html' %}
        {% endblock %}



    </div>
{% endblock body %}

{% block javascript %}
{% include 'adminlte/lib/_scripts.html' %}
{% block js %}{% endblock %}
{% endblock %}

{% block extra_js %}{% endblock %}

{% block extra_foot %}{% endblock %}
</body>
</html>

templates/adminlte/components/info_box.html
{% load humanize %}
<div class="info-box bg-{{ color }}">
    {% if not hide_icon %}
        <span class="info-box-icon"><i class="fa fa-{{ icon }}"></i></span>
    {% endif %}
    <div class="info-box-content">
        <span class="info-box-text">{{ header }}</span>
        <span class="info-box-number">{{ number }} {{ unit }}</span>
        {% if percent %}
            <div class="progress">
                <div class="progress-bar" style="width: {{ percent }}%"></div>
            </div>
            {% if how_long %}
                <span class="progress-description">
                    {{ percent }}% Increase in {{ how_long }}
                </span>
            {% endif %}
        {% endif %}
    </div><!-- /.info-box-content -->
</div><!-- /.info-box -->

templates/adminlte/example.html
{% extends 'adminlte/base.html' %}

{% block content %}
    <!-- Default box -->
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Title</h3>

            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                        title="Collapse">
                    <i class="fa fa-minus"></i></button>
                <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip"
                        title="Remove">
                    <i class="fa fa-times"></i></button>
            </div>
        </div>
        <div class="box-body">
            Start creating your amazing application!
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            Footer
        </div>
        <!-- /.box-footer-->
    </div>
    <!-- /.box -->
{% endblock %}

templates/adminlte/index.html
{% extends 'adminlte/base.html' %}

{% block content %}
your awesome content
{% endblock %}

templates/adminlte/lib/_main_footer.html
<footer class="main-footer">
        <div class="float-right d-none d-sm-block">
        {% block footer_right %}
            <b>Version</b> {% block version %}0.1{% endblock %}
        {% endblock %}
    </div>

    {% block footer_left %}
    {% block legal %}
    <strong>Copyright &copy; {% now "Y" %}{% if not site %}.{% endif %}
        {% if site %}
            <a href="http://{{ site.domain }}">{{ site.name }}</a>
        {% endif %}
    </strong> All rights
    reserved.
    {% endblock %}
    {% endblock %}
</footer>

templates/adminlte/lib/_main_header.html
{% load adminlte_helpers i18n %}
{% load static %}
<nav class="main-header navbar navbar-expand navbar-white navbar-light">


    <!-- Header Navbar: style can be found in header.less -->
    {% block nav_bar %}
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
        </li>
{#        <li class="nav-item d-none d-sm-inline-block">#}
{#            <a href="/" class="nav-link">Home</a>#}
{#        </li>#}
{#        <li class="nav-item d-none d-sm-inline-block">#}
{#            <a href="/admin" class="nav-link">Admin</a>#}
{#        </li>#}
    </ul>

    {% block nav_bar_center %}
    <!-- SEARCH FORM -->
{#    <form class="form-inline ml-3">#}
{#        <div class="input-group input-group-sm">#}
{#            <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">#}
{#            <div class="input-group-append">#}
{#                <button class="btn btn-navbar" type="submit">#}
{#                    <i class="fas fa-search"></i>#}
{#                </button>#}
{#            </div>#}
{#        </div>#}
{#    </form>#}
    {% endblock %}

    {% block nav_custom_menu %}
        <!-- Right navbar links -->
        <ul class="navbar-nav ml-auto">
            {% block header_dropdowns %}
              <!-- Messages Dropdown Menu -->
{#              <li class="nav-item dropdown">#}
{#                <a class="nav-link" data-toggle="dropdown" href="#">#}
{#                  <i class="far fa-comments"></i>#}
{#                  <span class="badge badge-danger navbar-badge">3</span>#}
{#                </a>#}
{#                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">#}
{#                  <a href="#" class="dropdown-item">#}
{#                    <!-- Message Start -->#}
{#                    <div class="media">#}
{#                      <img src="{%static 'admin-lte/dist/img/user1-128x128.jpg' %}" alt="User Avatar" class="img-size-50 mr-3 img-circle">#}
{#                      <div class="media-body">#}
{#                        <h3 class="dropdown-item-title">#}
{#                          Brad Diesel#}
{#                          <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>#}
{#                        </h3>#}
{#                        <p class="text-sm">Call me whenever you can...</p>#}
{#                        <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>#}
{#                      </div>#}
{#                    </div>#}
{#                    <!-- Message End -->#}
{#                  </a>#}
{#                  <div class="dropdown-divider"></div>#}
{#                  <a href="#" class="dropdown-item">#}
{#                    <!-- Message Start -->#}
{#                    <div class="media">#}
{#                      <img src="{%static 'admin-lte/dist/img/user4-128x128.jpg' %}" alt="User Avatar" class="img-size-50 img-circle mr-3">#}
{#                      <div class="media-body">#}
{#                        <h3 class="dropdown-item-title">#}
{#                          John Pierce#}
{#                          <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>#}
{#                        </h3>#}
{#                        <p class="text-sm">I got your message bro</p>#}
{#                        <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>#}
{#                      </div>#}
{#                    </div>#}
{#                    <!-- Message End -->#}
{#                  </a>#}
{#                  <div class="dropdown-divider"></div>#}
{#                  <a href="#" class="dropdown-item">#}
{#                    <!-- Message Start -->#}
{#                    <div class="media">#}
{#                      <img src="{%static 'admin-lte/dist/img/user3-128x128.jpg' %}" alt="User Avatar" class="img-size-50 img-circle mr-3">#}
{#                      <div class="media-body">#}
{#                        <h3 class="dropdown-item-title">#}
{#                          Nora Silvester#}
{#                          <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>#}
{#                        </h3>#}
{#                        <p class="text-sm">The subject goes here</p>#}
{#                        <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>#}
{#                      </div>#}
{#                    </div>#}
{#                    <!-- Message End -->#}
{#                  </a>#}
{#                  <div class="dropdown-divider"></div>#}
{#                  <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>#}
{#                </div>#}
{#              </li>#}
                <!-- Notifications Dropdown Menu -->
{#              <li class="nav-item dropdown">#}
{#                <a class="nav-link" data-toggle="dropdown" href="#">#}
{#                  <i class="far fa-bell"></i>#}
{#                  <span class="badge badge-warning navbar-badge">15</span>#}
{#                </a>#}
{#                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">#}
{#                  <span class="dropdown-item dropdown-header">15 Notifications</span>#}
{#                  <div class="dropdown-divider"></div>#}
{#                  <a href="#" class="dropdown-item">#}
{#                    <i class="fas fa-envelope mr-2"></i> 4 new messages#}
{#                    <span class="float-right text-muted text-sm">3 mins</span>#}
{#                  </a>#}
{#                  <div class="dropdown-divider"></div>#}
{#                  <a href="#" class="dropdown-item">#}
{#                    <i class="fas fa-users mr-2"></i> 8 friend requests#}
{#                    <span class="float-right text-muted text-sm">12 hours</span>#}
{#                  </a>#}
{#                  <div class="dropdown-divider"></div>#}
{#                  <a href="#" class="dropdown-item">#}
{#                    <i class="fas fa-file mr-2"></i> 3 new reports#}
{#                    <span class="float-right text-muted text-sm">2 days</span>#}
{#                  </a>#}
{#                  <div class="dropdown-divider"></div>#}
{#                  <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>#}
{#                </div>#}
{#              </li>#}
              <li class="nav-item">
                <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                  <i class="fas fa-expand-arrows-alt"></i>
                </a>
              </li>
            {% block user_info %}

            {% if request.user.is_authenticated %}
            <li class="nav-item dropdown user-menu">
                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                  <img src="{%avatar_url 128 %}" class="user-image img-circle elevation-2" alt="User Image">
                  <span class="d-none d-md-inline">{% firstof request.user.get_short_name request.user.get_username %}</span>
                </a>
                <ul class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                  <!-- User image -->
                  <li class="user-header bg-primary">
                    <img src="{%avatar_url size=160 %}" class="img-circle elevation-2" alt="User Image">

                    <p>
                        {% firstof request.user.get_short_name request.user.get_username %} - {% firstof request.user.get_role %}
                      <small>Member since : {{ request.user.date_joined }}</small>
                    </p>
                  </li>
                  <!-- Menu Body -->
                  <li class="user-body">
                    <div class="row">
                      <div class="col-4 text-center">
                        <a href="#">Profile</a>
                      </div>
                      <div class="col-4 text-center">
                        <a href="#">Team</a>
                      </div>
                      <div class="col-4 text-center">
                        <a href="#">Friends</a>
                      </div>
                    </div>
                    <!-- /.row -->
                  </li>
                  <!-- Menu Footer-->
                  <li class="user-footer">
                    <a href="{% block change_password_url %}{% url 'admin:password_change' %}{% endblock %}" class="btn btn-default btn-flat">{% trans 'Change Password'%}</a>
                    <a href="{% block logout_url %}{% logout_url %}{% endblock %}" class="btn btn-default btn-flat float-right">{% trans 'Sign Out'%}<a>
                  </li>
                </ul>
              </li>
            {% endif %}
            {% endblock user_info %}
            {% endblock header_dropdowns %}
        </ul>

    {% endblock nav_custom_menu %}

{% endblock %}
</nav>

templates/adminlte/lib/_main_sidebar.html
{% load adminlte_helpers %}
{%load static %}
<!-- Left side column. contains the sidebar -->
<aside class="main-sidebar sidebar-dark-primary  elevation-4">
     <!-- Brand Logo -->
    {% block logo %}
        <a href="/" class="brand-link">
            <img src="{%static 'image/logo.jpg' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
            {% block logo_text %}<span class="brand-text font-weight-light">地府管理系统</span>{% endblock %}
        </a>
    {% endblock %}
    <!-- sidebar: style can be found in sidebar.less -->
    <div class="sidebar">
        <!-- Sidebar user panel -->
        {% block user_panel %}
        <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{% avatar_url size=90 %}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">{% firstof request.user.get_full_name request.user.username %}</a>
        </div>
      </div>
        {% endblock %}

        {% block form %}{% endblock %}

        <!-- sidebar menu: : style can be found in sidebar.less -->
        {% block nav_links_ul %}
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">

            {% block nav_links %}
                {% for b_model, pages in menuInfo.items %}
                    {% if active == b_model %}
                        <li class="nav-item has-tree-view ">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-object-group"></i> <p>{{ b_model }}</p>
                                <p><i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview menu-open" style="display: block">
                                {% for page in pages %}
                                    {% if active_page == page.name %}
                                        <li>
                                            <a href="{{ page.url }}" class="nav-link active">
                                                <i class="nav-icon fas fa-circle"></i> {{ page.name }}
                                            </a>
                                        </li>
                                    {% else %}
                                        <li>
                                            <a href="{{ page.url }}" class="nav-link">
                                                <i class="nav-icon fas fa-circle"></i> {{ page.name }}
                                            </a>
                                        </li>
                                    {% endif %}
                                {% endfor %}
                            </ul>
                        </li>
                    {% else %}
                        <li class="nav-item has-tree-view " style="height: auto">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-object-group"></i> <p>{{ b_model }}</p>
                                <p><i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav-treeview" style="display: none">
                                {% for page in pages %}
                                   <li class="nav-item">
                                        <a href="{{ page.url }}" class="nav-link">
                                            <i class="nav-icon fas fa-circle"></i> {{ page.name }}
                                        </a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </li>
                    {% endif %}
                {% endfor %}
            {% endblock nav_links %}
            </ul>
            </nav>
        {% endblock nav_links_ul %}
    </div>
    <!-- /.sidebar -->
</aside>

templates/adminlte/lib/_messages.html
{% if messages %}
    {% for message in messages %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
        <div class="alert alert-success alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
        </div>
        {% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
        <div class="alert alert-danger alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
        </div>
        {% else %}
        <div class="alert alert-info alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
        </div>
        {% endif %}
    {% endfor %}
{% endif %}

templates/adminlte/lib/_pagination.html
{% if pager and ROOT_MENU.current_menu.view_name %}
    <ul class="pagination pagination-sm no-margin pull-right">
        <li><a href="{% url ROOT_MENU.current_menu.view_name %}?page=1&{{ pager.url_params }}">&laquo;</a></li>
        {% if pager.page > 2 %}
            <li>
                <a href="{% url ROOT_MENU.current_menu.view_name %}?page={{pager.page|add:-2}}&{{ pager.url_params }}">
                    {{ pager.page | add:-2 }}
                </a>
            </li>
        {% endif %}
        {% if pager.page > 1 %}
            <li>
                <a href="{% url ROOT_MENU.current_menu.view_name %}?page={{pager.page|add:-1}}&{{ pager.url_params }}">
                    {{ pager.page | add:-1 }}
                </a>
            </li>
        {% endif %}
        <li class="active"><a href="#">{{ pager.page }}</a></li>
        {% if pager.has_next %}
            <li>
                <a href="{% url ROOT_MENU.current_menu.view_name %}?page={{pager.page|add:1}}&{{ pager.url_params }}">
                    {{ pager.page | add:1 }}
                </a>
            </li>
        {% endif %}
        {% if pager.has_next_two %}
            <li>
                <a href="{% url ROOT_MENU.current_menu.view_name %}?page={{pager.page|add:2}}&{{ pager.url_params }}">
                    {{ pager.page | add:2 }}
                </a>
            </li>
        {% endif %}
        <li>
            <a href="{% url ROOT_MENU.current_menu.view_name %}?page={{pager.last_page}}&{{ pager.url_params }}">
            &raquo;
            </a>
        </li>
    </ul>
{% endif %}

templates/adminlte/lib/_scripts.html
{% load static %}

{% block scripts %}
<script src="{% static 'admin-lte/plugins/jquery/jquery.min.js' %}"></script>
<script src="{% static 'admin-lte/plugins/jquery-ui/jquery-ui.min.js' %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button);
</script>
<script src="{% static 'admin-lte/plugins/bootstrap/js/bootstrap.bundle.min.js' %} "></script>


{% block datatable_js %}{% endblock %}

<script src="{% static 'admin-lte/dist/js/adminlte.min.js' %}"></script>
<script src="{% static 'admin-lte/dist/js/demo.js' %}"></script>
{% endblock %}

templates/adminlte/lib/_styles.html
{% load static %}

{% block styles %}
<!-- Font Awesome -->
<link rel="stylesheet" href="{% static 'admin-lte/plugins/fontawesome-free/css/all.min.css' %}">
<!-- Ionicons -->
<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'admin-lte/dist/css/adminlte.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'admin-lte/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
{% endblock %}

templates/adminlte/pages/index.html
{% extends 'adminlte/base.html' %}

{% block content %}
    <div class="card">
        <div class="card-body">
            <table class="table table-bordered">
                <thead><tr>
                    <th>#</th>
                    <th>Title</th>
                    <th>Url</th>
                </tr>
            </thead>
            <tbody>
                {% for page in pager.items %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td><a target="_blank" href="{% url 'adminlte.example.pages' page_id=page.id %}">{{ page.title }}</a></td>
                        <td><a href="{% url 'adminlte.example.page.edit' page_id=page.id %}">编辑</a></td>
                    </tr>
                {% endfor %}
            </tbody>
            <thead><tr>
                <th>#</th>
                <th>Title</th>
                <th>Url</th>
            </tr>
        </thead>
            </table>
        </div>
        <!-- /.box-body -->
        <div class="card-footer clearfix">
            {% include 'adminlte/lib/_pagination.html' %}
        </div>
    </div>
{% endblock %}